### ISSUE TITLE
一些可以改进的地方

### ISSUE THREAD

**Issue by Zhouzhou-cloud** [jinyangl312/wos-selenium#2]
翻页会出错（从第一页到第二页）
网站网址变了，可以更新一下
在高级搜索时，没有结果会直接在当前页面出现alert，alert的语句有变化
有时某名奇妙在判断页面是否加载完成函数中断

**Comment by Zhouzhou-cloud** [comment]
楼主有联系方式吗？代码里没看到，有一些问题想请教一下。我先放个邮箱：jssyyrx@163.com。

**Comment by Zhouzhou-cloud** [comment]
有一个新的窗口组件，@id=pendo-close-guide-30f847dd“:Step 1 of 2”，不好关，一般2秒后才出现在页面中

**Comment by jinyangl312** [comment]
关于新的变化，您能提供样例吗，比如搜索的是什么呢？我也就是业余时间做一下，过于复杂的话可能难以维护了，如果简单的话，我可以添加一下。

**Comment by Zhouzhou-cloud** [comment]
大体上不需要改变很多。

**Comment by Zhouzhou-cloud** [comment]
具体讲，我也不是很能讲清，我就是运行，遇到问题再处理，修改了几处后，程序可以运行了（刨除了一两个功能）。
你是业余时间，我是业余人员，所以感觉你可能也就需要花个一个小时就能搞定。
我需要爬取信息，所以得用这程序。我现在正在添加代码，因为需要整理后的作者及其单位等信息以便进一步精确我的搜索结果（直接搜索的结果都是模糊匹配，而非精确匹配），在这过程中遇到一些问题想请教一下，就比如，这个outbound是啥意思？没能理解为啥用到这个词

**Comment by jinyangl312** [comment]
能正常运行就太好了。确实是这样，这个项目本身逻辑不复杂，但就是遇到了问题需要花时间耐心调试。

outbound，是WOS提供的检索文档的一个文本文件形式的记录。比如检索了某个关键词，然后搜索页面里有一个“Export”的按钮，这个就相当于outbound，主要是方便后续自动化提取信息用的。如果您没这个需求，可以忽略的。

**Comment by Zhouzhou-cloud** [comment]
外行，github不会玩，弄了一个Pull requests，有我修改后的东西，楼主如果想更新代码的话，希望我这个有用。
